### PR TITLE
added compat mode for tensorflow 2

### PR DESCRIPTION
**Pull request by udnaan**

### CODE REVIEW

**Comment by BramVanroy** [comment]
This requires a regression test, or at least a fix for BOTH versions, v1 as well as v2. As far as I can see, your pull request would only work for v2.

**Comment by BramVanroy** [comment]
Splendid. @nikitakit do you think this can be merged?

**Comment by HasanTuralic** [comment]
Could this be merged please?

**Comment by interrogator** [comment]
@nikitakit What's the holdup on this one? It preserves the old behaviour, so it's just a patch. And seems pretty straightforward. Would love if I didn't need to use a fork of this project when the PR's already done!

**Comment by michaeljohns2** [comment]
added #63 to test for v1 or v2. I testing in Databricks (was using GPU but should work for CPU the same).

**Comment by logicReasoner** [comment]
Is the performance with TF 2.2 better than with v1? I am wondering if I should upgrade now that we're compatible with 2.2

**Comment by mohdsanadzakirizvi** [comment]
Hi @nikitakit can we merge this soon as this is impacting the usability of benepar with tensorflow 2!

**Comment by jkgrad** [comment]
You can simplify the modification by simply replacing
`import tensorflow as tf` to `import tensorflow.compat.v1 as tf` from import. 

This can be done using shell command:
```sed -i 's/import tensorflow as tf/import tensorflow.compat.v1 as tf/g' ${PATH_TO_BENEPAR_BASE_PARSER.PY}```

**Comment by nikitakit** [comment]
This issue is fixed in benepar 0.1.3.

Starting with benepar 0.2.0a0, I've also switched to not using tensorflow at all. My original hope of having this package remain usable without any ongoing maintenance has sadly proven to be inadequate. Unfortunately modern ML code seems to have a short shelf-life -- meanwhile software like the EVALB program checked into this repo remains usable despite no changes over the course of a decade or more. With v0.2.0, I'm switching to a new approach where the code has more dependencies, but it's also easier to maintain because I'm using these same dependencies for my research and I have to keep up with software changes anyway. (This is different from tensorflow, which I don't use myself because I find pytorch and jax to better serve my research needs)

**Pull request closed without merging**
